trigger: none 

jobs:
- job:
  displayName: Verify Pull Requests
  pool: 
    name: TestSuiteBuildPool
  workspace:
    clean: false
  timeoutInMinutes: 0

  steps:
    - task: BatchScript@1
      displayName: 'Build ProtocolTestFramework'
      inputs:
        filename: 'src/build.cmd'